[toolchain]
anchor_version = "0.32.1"
solana_version = "1.18.17"

[features]
seeds = false
skip-lint = false

[programs.localnet]
tipchain_agent = "HEWsDJuFvTpofnKG6xiVshokK9oKQfpwwEqurKHAFP8F"

[programs.devnet]
tipchain_agent = "HEWsDJuFvTpofnKG6xiVshokK9oKQfpwwEqurKHAFP8F"

[programs.mainnet]
tipchain_agent = "HEWsDJuFvTpofnKG6xiVshokK9oKQfpwwEqurKHAFP8F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
